version: '3.3'
services:
  lineage:
    image: lineageos4microg/docker-lineage-cicd:latest
    environment:
      - BRANCH_NAME=lineage-20.0
      - DEVICE_LIST=cepheus
      - SIGN_BUILDS=true
      - PARALLEL_JOBS=8
      - TZ=Europe/Madrid
      - INCLUDE_PROPRIETARY=false
      - DELETE_OLD_ZIPS=1
      - DELETE_OLD_LOGS=1
      - CLEAN_OUTDIR=true
      - CLEAN_AFTER_BUILD=false
    volumes:
      - ~/lineage/src:/srv/src
      - ~/lineage/zips:/srv/zips
      - ~/lineage/logs:/srv/logs
      - ~/lineage/cache:/srv/ccache
      - ~/lineage/keys:/srv/keys
      - ~/lineage/manifests:/srv/local_manifests



